import * as React from 'react';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import tw from 'twin.macro';
import usePokedex from '@/lib/usePokedex';
import Card from '@/components/pokemon/Card';

const PageContainer = tw.div`flex flex-col justify-center items-center min-h-screen h-full bg-gray-200`;
const MainContainer = tw.main`flex items-center justify-center w-full py-12 px-20`;
const Footer = tw.footer`p-5 flex justify-center items-center w-full my-auto`;

const CardsContainer = tw.div`grid grid-cols-4 gap-10 justify-center items-center w-full`;

export default function Home() {
  const { getPokemons, getPokemonDetails } = usePokedex();
  const [data, setData] = React.useState([]);

  const fetchPokemons = async () => {
    const list = await getPokemons();

    if (!list.error) {
      const promises = [];
      const pokemons = [];

      list.data.forEach((pokemon) => {
        const pokemonDetailsPromise = getPokemonDetails(pokemon.name).then(
          (result) => !result.error && pokemons.push(result.data)
        );
        promises.push(pokemonDetailsPromise);
      });

      await Promise.allSettled(promises);

      console.log(pokemons);

      setData(pokemons);
    }
  };

  React.useEffect(() => {
    fetchPokemons();
  }, []);

  return (
    <PageContainer>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <MainContainer>
        <CardsContainer>
          {Array.isArray(data) && data.length > 0 && data.map((d) => <Card pokemon={d} />)}
        </CardsContainer>
      </MainContainer>

      <Footer>
        <a
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          target='_blank'
          rel='noopener noreferrer'>
          Powered by{' '}
          <span className={styles.logo}>
            <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
          </span>
        </a>
      </Footer>
    </PageContainer>
  );
}
